template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.myRepo.gitProvider }}                       # <-- replace with your integration
      path: {{ .Values.myRepo.path }}   # <-- replace with your repository name
      branches:
        include: master  
  - name: al_image
    type: Image
    configuration:
      registry: {{ .Values.alArtifact.intkey }}       
      sourceRepository: {{ .Values.alArtifact.srepo }}
      imageName: {{ .Values.alArtifact.image }}
      imageTag: latest
      autoPull: true
  - name: al_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.alArtifact.intkey }}
      buildName: al_build
      buildNumber: 1
  - name: myPropertyBag
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
pipelines:
  - name: build_base_image
    steps:
      - name: docker_build_al
        type: DockerBuild
        configuration:
          affinityGroup: al_group
          dockerFileLocation: .
          dockerFileName: {{ .Values.alArtifact.file }}
          dockerImageName: {{ .Values.alArtifact.image }}
          dockerImageTag: ${run_number}
          inputResources:
            - name: dbp_repo
          integrations:
            - name: {{ .Values.alArtifact.intkey }}
      - name: docker_push_al
        type: DockerPush
        configuration:
          affinityGroup: al_group
          targetRepository: {{ .Values.alArtifact.srepo }}
          integrations:
            - name: {{ .Values.alArtifact.intkey }}
          inputSteps:
            - name: docker_build_al
          outputResources:
            - name: al_image
      - name: publish_al_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push_al
          outputResources:
            - name: al_build_info
  - name: my_second_pipeline
    steps:
      - name: p2_s1
        type: Bash
        configuration:
          inputResources:
            # Sets up step to be triggered when myPropertyBag is updated
            - name: myPropertyBag
        execution:
          onExecute:
            # Retrieves the commitSha from input resource
            - echo "CommitSha is $res_myPropertyBag_commitSha"
