myRepo:
  gitProvider: mygt
  path: nikhil-oss/glden-image

alArtifact:
  srepo: clod-base-os
  image: eurekahealth.jfrog.io/clod-base-os/al-base-image
  file: Dockerfile
  intkey: myart
  
osName:
  python: python-3.10
